name: Lint Code Base

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install isort black

      - name: Run isort
        run: |
          isort --check-only .

      - name: Run Black
        run: |
          black --check .

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - name: Run Tests
        env:
          DJANGO_SETTINGS_MODULE: cakeaddicts.settings  # Ensure this points to your settings module
          PYTHONPATH: ${{ github.workspace }}
        run: |
              pytest cakestore/test  # Ensure this points to your test folder path
          
